### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for BrMaskerIonic3: (?, ?).

### ISSUE THREAD

**Issue by lfxsantos** [amarkes/br-masker-ionic-3#12]
Could you help me with this error?

**Comment by amarkes** [comment]
more details

**Comment by lfxsantos** [comment]
Eu apenas inclui no arquivo app.module.ts 

`import { BrMaskerModule } from 'brmasker-ionic-3';`

```
@NgModule({
  declarations: [
  ...
  ],
  imports: [
   ...
    BrMaskerModule  
  ],
```

**Comment by lfxsantos** [comment]
![image](https://user-images.githubusercontent.com/12746682/32187852-59098f7a-bd8d-11e7-9061-05d92b3467cf.png)

**Comment by amarkes** [comment]
Talvez possa ser as versões...
[requerid versions](https://github.com/amarkes/br-masker-ionic-3#required)

**Comment by lfxsantos** [comment]
Beleza. Vou atualizar o node. 
Esse ionic 3.9.2 que você diz é o cli?

**Comment by lfxsantos** [comment]
O erro continua com
node 8.8.1
npm 5.4.2
ionic 3.15.2

**Comment by amarkes** [comment]
compartilha o código que esta usando?

**Comment by lfxsantos** [comment]
Então, eu nem cheguei a codificar nada nas páginas.
O erro acontece só de incluir o BrMaskerModule   no app.module

**Comment by rafaneri** [comment]
A mesma coisa por aqui... Basta incluir o BrMaskerModule no app.module.ts

**Comment by amarkes** [comment]
This was a bug found when compiling at the npm, it has already been fixed and I ask you to upgrade to test again.

**Comment by rafaneri** [comment]
Thank you @amarkes!
I have tested and now it works.
