### ISSUE TITLE
Bug cpf!

### ISSUE THREAD

**Issue by Shelps** [amarkes/br-masker-ionic-3#13]
Try this cpf 05777599090, after formatting 057.775.99090.

**Comment by amarkes** [comment]
![captura de tela 2017-11-13 as 10 55 34](https://user-images.githubusercontent.com/6019683/32726747-381e4dc6-c861-11e7-9a97-285a4ae4e505.png)

**Comment by Shelps** [comment]
This happens when I shoot the focus, try this! please

**Comment by amarkes** [comment]
update your plugins
