### ISSUE TITLE
somente números

### ISSUE THREAD

**Issue by guilhermedclima** [amarkes/br-masker-ionic-3#14]
Boa noite
parabéns pela iniciativa, como é um repo br nada melhor que perguntar em br kkk
teria alguma forma de por exemplo o validator cif/cnpj person:true ... só aceitar números ?

**Comment by amarkes** [comment]
update your plugins (y)

**Comment by VictorAssis** [comment]
I installed the latest version with the command below, but the error continues.
```
npm install brmasker-ionic-3@latest --save
```

My input is declared as follows:
```
<ion-input
    type="text"
    value=""
    placeholder="INFORME O CPF"
    [brmasker]="{mask:'999.999.999-99', len:14}"
    [(ngModel)]="data.cpf">
</ion-input>
```
