### ISSUE TITLE
Problema com ion-inputs de ""type=number"

### ISSUE THREAD

**Issue by ShadTK** [amarkes/br-masker-ionic-3#15]
Issue ocorre ao usar um ion-input com type=number ao invés de type=text

Exemplo:
              <ion-input
                type="number"
                name="document"
                id="document"
                autocapitalize="none"
                [(ngModel)]="user.login"
                [brmasker]="{person: true}"
                #document="ngModel"
                #documentFocus
                required><ion-icon name="heart"></ion-icon>
              </ion-input>

Ao digitar o oitavo digito do CPF, o input é apagado e a seguinte log aparece no console:

brmasker-ionic-3.js:20 The specified value "412.341.23" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?

Ao selecionar input=text, o problema é resolvido.

Seria possivel incluir suporte para type=number?

Regards
Marcos

**Comment by Gaabe** [comment]
@ShadTK Nenhum dos modulos de mask para ionic que eu testei funcionam com inputs type="number", se você quiser utilizar uma mascara e quer que aparece o teclado numérico, sugiro que o input type="tel", é o que eu tenho usado para contornar esse problema.

**Comment by itlpps** [comment]
Tenta por type="tel", o teclado aparecerá numérico.

**Comment by ShadTK** [comment]
Ok, por type tel funciona. Thx pelo heads up!
