### ISSUE TITLE
Accept more digits

### ISSUE THREAD

**Issue by RaunyHenrique** [amarkes/br-masker-ionic-3#17]
I use this mask:
<ion-input [brmasker]="{mask:'00.000-000', len:10}" type="text" [(ngModel)]="entity.endereco.cep" formControlName="cep" (ionChange)="getEndereco()"></ion-input>

But the input accept more than 10 digits.. example: "58.417-7539" or "58.417-753978".

I already used another mask component, and it had the same problem. Is there any solution to this bug?

**Comment by amarkes** [comment]
It's very simple, use len = 11, len is the amount of characters the mask will use
[brmasker]="{mask:'00.000-000', len:11}" or [brmasker]="{mask:'00.000-000', len:13}"
I'll soon warn you that for ionic it does not support ngModel
ngModel there is a bug regarding data that were not typed, so the special characters are not typed it gives an error that we still do not find a solution for it, I recommend using only the ReactiveForm

**Comment by RaunyHenrique** [comment]
I know, but I want the input ONLY to receive 10 digits (ex: 58.417-753). I removed NgModel, I used ReactiveForm, but the problem persists. 
If I type a digit longer than the size of the mask, the input accepts this value.

**Comment by allys00** [comment]
if I enter any number more, it erased from the view but continues the value

**Comment by amarkes** [comment]
use maxlength `<input maxlength="">`

**Comment by rafaellaurinemeira** [comment]
Try this:
<ion-input 
[brmasker]="{mask:'00.000-000', len:10}" 
**maxLength: 10,**
type="text" 
[(ngModel)]="entity.endereco.cep"
formControlName="cep" 
(ionChange)="getEndereco()">
</ion-input>

**Comment by amarkes** [comment]
this was corrected in the version 1.0.6
```
npm i --save brmasker-ionic-3@1.0.6
```

if you have solved, close issue?
