### ISSUE TITLE
Problemas no valor de moeda

### ISSUE THREAD

**Issue by victorhramos** [amarkes/br-masker-ionic-3#18]
O valor retornado pelo [(ngModel)] vem diferente do renderizado no input, segue anexo do console:

Ps* O log foi feito a partir do evento ionChange
![image](https://user-images.githubusercontent.com/9410768/34028469-8366fc5e-e14a-11e7-895a-c730cda8f938.png)

**Comment by marcusdurao** [comment]
Comigo aconteceu a mesma coisa. Existe alguma solução ?

Obrigado

**Comment by felipecastro2607** [comment]
Comigo também aconteceu a mesma coisa. Formata a moeda direitinho mas na hora que os dados são submetidos, ocorre essa divisão por 10.

**Comment by amarkes** [comment]
Ainda não tem como fazer para dar suporte para o ngModel, apenas para o reactiveform

**Comment by wilsoncx** [comment]
Eu uso o reactive mas na hora que envia o valor também vai assim.

**Comment by amarkes** [comment]
Isso foi resolvido na versao 1.0.6
```
npm i --save brmasker-ionic-3@1.0.6
```

**Comment by jimmyrleung** [comment]
Estou utilizando a versão 1.0.9 e o problema continua:

![image](https://user-images.githubusercontent.com/22828137/39537957-8695a360-4e11-11e8-8ad1-5b1073ea0e52.png)

Alguem tem alguma solução?

**Comment by amarkes** [comment]
bem estranho, isso já foi corrigido, e acabei de testar e esta funcionando de boa... so vendo para saber o q aconteceu ai

**Comment by jimmyrleung** [comment]
estou pegando através de input/ionChange
`
<ion-input type="text" [(ngModel)]="preco" (ionChange)="recalculaQuantidade()" name="price" placeholder="{{ 'COMPRAVENDA PLACEHODER DISTANCE' | translate }}"></ion-input>
`

E o código no component:
`
recalculaQuantidade() {
    console.log(this.preco);
    console.log(Helpers.stringToPrice(this.preco));
  }
`

**Comment by amarkes** [comment]
nem da suporte ao ngModel ainda...

**Comment by jimmyrleung** [comment]
Ahhh entendi, achei que tinha sido corrigido o cenário do post feito pelo victorhramos, foi malz, vou testar via reactive forms

**Comment by Lukiita** [comment]
Estou com um problema em relação a teclados Samsung. Coloquei uma máscara de cpf conforme abaixo:

        <ion-input autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" formControlName="cpf" [brmasker]="{mask:'000.000.000-00', len:14, type:'num'}"></ion-input>
     

Tudo funciona bem quando testo no browser, porém quando coloco em um celular da SAMSUNG com o teclado da SAMSUNG eu começo a ter problemas. Depois que digito o quarto ou quinto caractere o input é autocompletado com numeros aleatórios. Já viram esse problema em outro lugar? Tem alguma solução?

**Comment by plauzul** [comment]
Estou tendo o mesmo problema do @Lukiita alguma solução algum tipo de hack? Qualquer coisa? Estou usando a versão 1.1.0

**Comment by amarkes** [comment]
Fui ver o lance do teclado da Samsung, então achei assa issue

assisrafael/angular-input-masks#242

————————————————-

The issue was solved using input with type="tel". It was tested in Samsung Keyboard, GBoard and Android Keyboard 4.4.4.

The problem was the keyboard response, if input's type was text, the keyboard change between alphanumeric keyboard and numeric keyboard. That behaviour breaks the moment when the code got the cursor position and set.

After that change, the keyboard not change and stay on numeric keyboard fixing the issue.
