### ISSUE TITLE
Can't bind to 'brmasker' since it isn't a known property of 'ion-input'.

### ISSUE THREAD

**Issue by phablulo** [amarkes/br-masker-ionic-3#19]
Olá!
Eu importei assim como está descrito na documentação:
```
import { BrMaskerModule } from 'brmasker-ionic-3';

@NgModule({
  imports: [
    BrMaskerModule
  ],
})
```

Contudo, obtenho erro quando tento usá-lo no ion-input:

```
Uncaught Error: Template parse errors:
Can't bind to 'brmasker' since it isn't a known property of 'ion-input'.
1. If 'ion-input' is an Angular component and it has 'brmasker' input, then verify that it is part of this module.
2. If 'ion-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
	<ion-item>
		<ion-label floating>CEP</ion-label>
		<ion-input #cep type="text" [ERROR ->][brmasker]="{mask:'000.000.000-00', len:14}" [(ngModel)]="endereco.cep" (keyup)="watchcep($event)"></")
```

Eu tenho de fazer algo a mais para poder usar o brMasker?
Estou usando ionic 3.19.0

Obrigado

**Comment by lucksma96** [comment]
Pra mim também não funcionou assim. Tu vai ter que importar no module da página em que tu quer usar. Se tu estiver usando a Ionic CLI, tu pode ver que além de gerar o .html, .scss e .ts da página, ela gera um .module.ts, é nele.
Mas eu recomendo tu pode criar um módulo onde tu importa as coisas que tu precisa nas páginas (como o plugin) e daí importa ele nos módulos delas, assim, todas as mudanças necessárias ficam concentradas nele.

**Comment by lucksma96** [comment]
Estrutura de uma página:
![image](https://user-images.githubusercontent.com/11969528/34520753-487b55fa-f071-11e7-8ec6-e70edead9ffe.png)

Módulo da página importando módulo de componentes:
![image](https://user-images.githubusercontent.com/11969528/34520767-65ac1862-f071-11e7-9a14-d8f1c808d76b.png)

**Comment by phablulo** [comment]
Entendi!
Eu estava importando no app.module.ts

Muito obrigado, @lucksma96  :)
