### ISSUE TITLE
BrowserModule has already been loaded.

### ISSUE THREAD

**Issue by dtgfranca** [amarkes/br-masker-ionic-3#2]
Estou com um problema à dois dias e não consigo resolver. Fiz a importação da mascara  BrMaskerModule no ngModules, mas quando vou utilizá-la gera esse error:
" BrowserModule has already been loaded. If you need access to common directives "
Já tentei importar o Commom mas não adiantou.

Informações adicionais:
cli packages: (/usr/lib/node_modules)

   @ionic/cli-utils  : 1.12.0
   ionic (Ionic CLI) : 3.12.0

global packages:

   cordova (Cordova CLI) : 6.5.0

local packages:

   @ionic/app-scripts : 2.1.4
   Cordova Platforms  : android 6.1.2
   Ionic Framework    : ionic-angular 3.6.1

System:

   Android SDK Tools : 25.2.5
   Node              : v7.10.1
   npm               : 4.2.0
   OS                : Linux 4.8

**Comment by amarkes** [comment]
Ele está alegando que o BrowserModule ja foi carregado, só com essas informações não vou conseguir lhe ajudar muito... pega meu email vamos nos falando por la...

**Comment by dtgfranca** [comment]
Obrigado, amigo! Eu descobri o erro, não era na mascara, mas sim no meu código. Resolvido!
