### ISSUE TITLE
nonspecific mask doesn't work

### ISSUE THREAD

**Issue by rafaellaurinemeira** [amarkes/br-masker-ionic-3#20]
**Type text:**
`<ion-input type="text" name="cep" [brmasker]="{mask:'00.000-000', len:10}" maxLength=10>`
ab.cde-fgh

**Type tel:**
`<ion-input type="tel" name="cep" [brmasker]="{mask:'00.000-000', len:10}" maxLength=10>`
NN.NNN-NNN
;;.;;;-;;;

**Comment by amarkes** [comment]
we checked, and your mask is right.
