### ISSUE TITLE
Problemas com números

### ISSUE THREAD

**Issue by jorgerabello3** [amarkes/br-masker-ionic-3#22]
Boa noite .
Eu precisaria de um input com o type de number algo como 

```
<ion-item class="input-item">
    <ion-label stacked>CPF</ion-label>
    **<ion-input type="number" formControlName="cpf" placeholder="CPF" [brmasker]="{mask:'000.000.000-00', len:14}" value=""></ion-input>**
</ion-item>
```

Mas notei que a máscara só funciona com text... Há alguma forma de fazer funcionar com number ?

Grato

-----------------------------------------------------------------------------------
Good evening .
I would need an input with type of number something like

```
<ion-item class="input-item">
    <ion-label stacked>CPF</ion-label>
    **<ion-input type="number" formControlName="cpf" placeholder="CPF" [brmasker]="{mask:'000.000.000-00', len:14}" value=""></ion-input>**
</ion-item>
```
But I noticed that the mask only works with text ... Is there any way to make it work with number?

thankful

**Comment by amarkes** [comment]
Neste caso tente usar o 
```
<ion-item>
        <ion-input type="text" formControlName="person" name="cpf" placeholder="CPF" [brmasker]="{person: true}"></ion-input>
      </ion-item>
```
o person: true ele vai criar uma mascara de cpf/cnpj

se resolver fecha a issue?
