### ISSUE TITLE
Phone problem

### ISSUE THREAD

**Issue by felipebluiz** [amarkes/br-masker-ionic-3#25]
**This is normal?**
![em1moqknresojpbnls1avg](https://user-images.githubusercontent.com/27743679/36079444-04d5091e-0f6a-11e8-82a6-7ccfdc65bc5b.png)

)
**My input:**
<ion-input type="tel" name="tel" [brmasker]="{phone: true}" maxLenght="15" required>

**Comment by amarkes** [comment]
Normal não é! Mais o que usar para pegar o que foi digitado? ngModel, ReactiveForm?

**Comment by felipebluiz** [comment]
ngModel

**Comment by amarkes** [comment]
Infelizmente o ngModel não respeita bem o Renderer do angular, tenta usar o reactiveform...

**Comment by felipebluiz** [comment]
![screenshot_1](https://user-images.githubusercontent.com/27743679/36119904-967c5552-1028-11e8-843a-3b10ac71eea7.png)

Mesmo erro usando ReactiveForm.
Codigo HTML:
`<form [formGroup]="form" (ngSubmit)="onSubmit()" novalidate>
    <ion-item>
        <ion-label color="primary" stacked>Nome completo</ion-label>
        <ion-input type="text" formControlName="name"></ion-input>
    </ion-item>
    <ion-item>
        <ion-label color="primary" stacked>DDD + Telefone</ion-label>
        <ion-input type="tel" formControlName="phone" [brmasker]="{phone: true}"></ion-input>
    </ion-item>
    <button ion-button full type="submit">Submit</button>
</form>`

**Comment by amarkes** [comment]
Atualiza essa birosca para 1.0.6 para ver se vai dá!

**Comment by felipebluiz** [comment]
Perfeito!! Muito obrigado.
