### ISSUE TITLE
Can't bind to 'brmasker' since it isn't a known property of 'ion-input'.

### ISSUE THREAD

**Issue by ronaldaraujo** [amarkes/br-masker-ionic-3#26]
Instalei via npm, coloquei no **imports** do meu arquivo **app.module.ts**, porém estou obtendo o seguinte erro:
![image](https://user-images.githubusercontent.com/1413455/36178686-745a7910-10f8-11e8-9abc-d556fee1a737.png)

**app.module.ts**
```
...
import { BrMaskerModule } from 'brmasker-ionic-3';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    ListPage
  ],
  imports: [
    BrowserModule,
    BrMaskerModule,
    IonicModule.forRoot(MyApp)
  ],
...
```

**minhapagina.html**
```
...
<ion-item>
    <ion-label floating>CPF</ion-label>
    <ion-input type="text" formControlName="cpf" [brmasker]="{mask:'000.000.000-00', len:14}"></ion-input>
</ion-item>
...
```
O que pode ser?

**Comment by amarkes** [comment]
mais porque tem os asteriscos no import do **BrMaskerModule** ?

**Comment by ronaldaraujo** [comment]
@amarkes, na verdade era pra ser negrito só que a formatação não funcionou devido a formatação de código...

**Comment by amarkes** [comment]
entao cara, isso está certo! a principio isso pode ser de ambiente, já tentou restarta a aplicação?

**Comment by ronaldaraujo** [comment]
Já! Várias vezes. Já mudei de navegador. Já gerei um apk pra rodar no cel, mas até agora nada. A título de informação estou usando a ultima versão do **Ionic 3.19.1**.

**Comment by amarkes** [comment]
Vou te mandar um e-mail

**Comment by ronaldaraujo** [comment]
A solução encontrada foi importar no arquivo minhapagina.module.ts

...
import { BrMaskerModule } from 'brmasker-ionic-3';

@NgModule({
  declarations: [
    SettingsPage,
  ],
  imports: [
    IonicPageModule.forChild(SettingsPage),
    BrMaskerModule
  ],
})
export class SettingsPageModule {}
...

@amarkes, obrigado tela atenção :+1:
