### ISSUE TITLE
(focus) and (blur) deprecated

### ISSUE THREAD

**Issue by juliansci** [amarkes/br-masker-ionic-3#27]
Hi! Today saw the next alerts on console:
(focus) is deprecated in ion-input, use (ionFocus) instead
(blur) is deprecated in ion-input, use (ionBlur) instead

Thanks!

**Comment by amarkes** [comment]
this version 1.0.6 use ionFocus and ionBlur
![captura de tela 2018-02-15 as 11 02 16](https://user-images.githubusercontent.com/6019683/36257860-baa8dca2-123f-11e8-881b-1663f31df542.png)
