### ISSUE TITLE
Mascara para hora 00:00

### ISSUE THREAD

**Issue by andredatsch** [amarkes/br-masker-ionic-3#28]
Não estou conseguindo colocar uma mascara para hora no tipo 00:00 

Para todos os outros casos está funcionando corretamente

**Comment by amarkes** [comment]
Como está usando?

**Comment by andredatsch** [comment]
<ion-item class="select-form enableBottomBorder" *ngIf="showAdd == true">
            <ion-label color="primary">Horário de atendimento:</ion-label>
            <ion-input type="text" [brmasker]="{mask:'00:00', len:5}"  type="tel"></ion-input>
        </ion-item>

**Comment by andredatsch** [comment]
o type eu tava tentando mudar, não funcionou com number tambem

**Comment by andredatsch** [comment]
Pelo que eu vi não tem o ":" na lista de caracteres disponiveis:  - . / ( ) , * + @ # $ & %

**Comment by amarkes** [comment]
Com type text não dá?

**Comment by andredatsch** [comment]
Não sr.

**Comment by andredatsch** [comment]
@amarkes  existe alguma previsão de correção?

**Comment by amarkes** [comment]
`npm i --save brmasker-ionic-3@latest`
