### ISSUE TITLE
Campos estão aceitando letras

### ISSUE THREAD

**Issue by wesleycavalcante** [amarkes/br-masker-ionic-3#30]
Alterei o arquivo brmasker-ionic-3.js linha 124 para:

var exp = /\-|\.|\/|\(|\)|\,|\*|\+|\@|\#|\$|\&|\%|\:| |[A-Za-z]/g;

**Comment by amarkes** [comment]
O que de fato esta querendo fazer?
Seja mais especifico, talvez uma solução para ti, pode não ser uma solução para os outros.

**Comment by wesleycavalcante** [comment]
Minha máscara era 00.0000.00000000-0 e estava permitindo colocar letras quando eu queria apenas números

**Comment by amarkes** [comment]
Existem pessoas que usam a mascara com letra, fazendo dessa forma, prejudica os que já usam, o que pode ser feito é passar mais uma configuração informando se usaria so numero ou so letra ou os dois...

**Comment by verissimomanoel** [comment]
Eu acredito que seria legal colocar esse parametro mesmo, pois por exemplo: máscara de CPF só aceita número, não faz sentido aceitar letras. Eu estou tentando usar a biblioteca e estou tendo a mesma dificuldade.

**Comment by verissimomanoel** [comment]
Uma maneira de resolver o problema é fazer com no celular só apareça o teclado numérico, assim o usuário não conseguirá digitar letras. Eu fiz isso aqui e resolveu o meu problema, segue abaixo o exemplo:
<ion-input type="text" pattern="\\d*" name="login" title="Login" [brmasker]="{mask:'000.000.000-00', len:14}"></ion-input>

**Comment by jeffersonmello** [comment]
@verissimomanoel 
poderia explicar melhor como utilizar os teclados numéricos/textuais?

**Comment by amarkes** [comment]
@verissimomanoel para cif já existe um tratamento para isso
`[brmasker]="{person: true}"`

**Comment by verissimomanoel** [comment]
Bom o problema relatado era que ao colocar uma máscara, por exemplo de CPF, aceitava digitar letras. Então se colocar o parametro pattern="\d*" o ionic abre somente o teclado numérico e nesse caso além de resolver o problema melhora a usabilidade do app.

**Comment by amarkes** [comment]
Fiz uma novar versao com o campo type `| type | string | Optional default 'all' |`

`alfa` => alfanuméricos
`num` => números
`all` => aceita a porra toda

Exemple

```
[brmasker]="{mask:'00/00/0000', len:10, type:'num'}"
```

**Comment by verissimomanoel** [comment]
@amarkes ainda com esse parâmetro, recomendo o uso do pattern, pois como só vai aceitar número no campo então, abrir somente o teclado numérico ajuda na usabilidade.

**Comment by amarkes** [comment]
Caso seja resolvido, podem fechar a issue?

**Comment by verissimomanoel** [comment]
Por mim já pode fechar.

**Comment by jeffersonmello** [comment]
@verissimomanoel  obrigado pela explicação, por min closed

**Comment by wesleycavalcante** [comment]
Por mim pode fechar.

**Comment by juniorsistemasufms** [comment]
Pessoal acompanhei as postagem porém estou tentando fazer  o type num do CPF no formato 999.999.999-99  porém abrindo somente o teclado numérico..   e não consegui.
se coloco ion-input para number abre o teclado numerico porém a mascara não funciona.(obviamente acho que ela faz o que deve não permitir caracteres)

contudo queria ver um meio termo

mascara :: 999.999.999-99  abrindo o teclado numerico somente  será q tem como ?

**Comment by amarkes** [comment]
Junior tenta o type tel

**Comment by TICBXCEOX** [comment]
> Eu acredito que seria legal colocar esse parametro mesmo, pois por exemplo: máscara de CPF só aceita número, não faz sentido aceitar letras. Eu estou tentando usar a biblioteca e estou tendo a mesma dificuldade.

CPF's antigos aceitam letras também, ex., o 'X'
