### ISSUE TITLE
Salvando com 3 casas decimais no reactive form

### ISSUE THREAD

**Issue by rodrigoords** [amarkes/br-masker-ionic-3#40]
Estou usando a mascara para um campo de valor conforme o exemplo:

`      <ion-item *ngIf="showAmountToReceive">
          <ion-label stacked>Valor à receber</ion-label>
          <ion-input type="tel" name="money"  placeholder="0,00" [brmasker]="{money: true, decimal: 2}" clearInput formControlName="recebimento"></ion-input>
      </ion-item>`
 
 Quando se está digitando é mostrado normal o valor com a mascara correta, com dois decimais, porém quando busco o valor salvo dentro do form ele está com três decimais, quando eu volto a renderizar o valor na tela ele é mostrado com três decimais e a mascara só é corrigida quando volto o foco para o campo.

Exemplo: 
 Valor na tela: 1000,00
 Valor no form: 100,000

Versão: 1.0.9

**Comment by amarkes** [comment]
atualiza para 1.0.10 e tenta usar assim https://github.com/amarkes/br-masker-ionic-3#features
