### ISSUE TITLE
Problema com a formatação

### ISSUE THREAD

**Issue by raphagood** [amarkes/br-masker-ionic-3#42]
Boa tarde!

  Estou utilizando br-masker no meu projeto, e todos os campos que estou formatando estão dando problema, quando testo no dispositivo, ao começar a preencher o campo... as informações são preenchidas automaticamente de forma involuntária, percebi que em um dado momento ele repete tudo a partir do 4º caractere.

  Não faço a minima idéia do que possa ser isso, alguém ai já passou pelo mesmo problema?

Atenciosamente.

**Comment by jeffersonmello** [comment]
Comigo isso também acontece, se alguem tiver alguma solução o problema é critico

**Comment by amarkes** [comment]
como esta usando isso?

**Comment by jeffersonmello** [comment]
de forma comun:

`<ion-item>
	<ion-input type="text" name="phone" placeholder="Phone" [brmasker]="{phone: true}"></ion-input>
</ion-item>`

**Comment by amarkes** [comment]
me parece esta certo, mais testei e não achei nada que possa acontecer isso, teria como me mostrar um exemplo?

**Comment by jeffersonmello** [comment]
na hora que estiver com um aparelho te mostro no emulador nao acontece somente no device mesmo

**Comment by cleitonsoares** [comment]
Estou com o mesmo problema, utilizando a mesma máscara:
`<ion-input name="fone" [(ngModel)]="customer.tel_cel_paciente" [brmasker]="{phone: true}"></ion-input>`

Esse input está dentro de um ngForm:
`<form #form="ngForm" id="ngForm" (ngSubmit)="saveCustomer(form)" novalidate>`

No print abaixo vc consegue ver o que foi digitado e o resultado no campo telefone:

![screenshot_2018-05-03-20-22-11](https://user-images.githubusercontent.com/16797038/39607214-17781990-4f10-11e8-9c74-2721ce872557.png)

**Comment by amarkes** [comment]
Já tentou reactiveForm?

**Comment by amarkes** [comment]
Foi criado uma função para tentar resolver o uso do NgModel, veja as [Features](https://github.com/amarkes/br-masker-ionic-3#features)

**Comment by jeffersonmello** [comment]
Este problema acontece apenas em teclados da samsung, outros plugins de mascara ocorre o mesmo erro

**Comment by raphagood** [comment]
Boa noite, Pessoal!

  Até o momento não consegui resolver, a lib é bem legal mas este problema inviabiliza a sua utilização, alguém tem a solução definitiva para o problema?

Atenciosamente.

**Comment by amarkes** [comment]
The issue was solved using input with type="tel". It was tested in Samsung Keyboard, GBoard and Android Keyboard 4.4.4.

Fui ver o lance do teclado da Samsung, então achei assa issue 

https://github.com/assisrafael/angular-input-masks/issues/242

————————————————-
The problem was the keyboard response, if input's type was text, the keyboard change between alphanumeric keyboard and numeric keyboard. That behaviour breaks the moment when the code got the cursor position and set.

After that change, the keyboard not change and stay on numeric keyboard fixing the issue.

**Comment by raphagood** [comment]
Muito obrigado @amarkes funcionou perfeitamente mudando o tipo do campo para 'tel', nem sei como agradecer, agora esta tudo perfeito :)
