### ISSUE TITLE
[brmasker]="{money: true, decimal: 0}" is not working :(

### ISSUE THREAD

**Issue by Chethannp** [amarkes/br-masker-ionic-3#43]
[brmasker]="{money: true, decimal: 0}" is not working it is forcefully appending 2 decimal points and also is there a way to change the representation as '199.00' rather than '199,00' since it is a decimal point.

**Comment by amarkes** [comment]
to what a zero decimal?

**Comment by amarkes** [comment]
check version 1.0.11
