### ISSUE TITLE
change the value of 'brmask' by the value of the variable

### ISSUE THREAD

**Issue by raphaelluiz128** [amarkes/br-masker-ionic-3#53]
i used this plugin

my idea is to change the value of 'brmask' by the value of the variable, but it don't work.

error
vendor.js:1782 ERROR Error: Uncaught (in promise): TypeError: Cannot create property 'type' on string '{mask:'000.000.000-00', len:14}'
TypeError: Cannot create property 'type' on string '{mask:'000.000.000-00', len:14}'

ts

  Mcpfcnpj: string = "{mask:'000.000.000-00', len:14}";

html

 <ion-item>
        <ion-label floating>{{CPF_CNPJ}} </ion-label>
        <ion-input type="text" style = 'width:80%' [(ngModel)]="user.cpf_cnpj" [brmasker]="Mcpfcnpj"></ion-input>
    </ion-item>

**Comment by raphaelluiz128** [comment]
Please close it.

i altered this code
Mcpfcnpj: string = "{mask:'000.000.000-00', len:14}";

for 

Mcpfcnpj: any = {mask:'000.000.000-00', len:14};

and its work

**Comment by amarkes** [comment]
eu não entendi o que foi feito...
