### ISSUE TITLE
[Ionic 4]  More than one custom value accessor

### ISSUE THREAD

**Issue by MrSparklle** [amarkes/br-masker-ionic-3#55]
Estou migrando um app de Ionic 3 para versão 4 e quando habilito o plugin começa gerar o erro abaixo:

```
ERROR Error: Uncaught (in promise): Error: More than one custom value accessor matches form control with unspecified name attribute
```

No meu teste estou usando uma máscara simples de telefone num campo de input:
`<ion-input formControlName="phone" type="tel" [brmasker]="{phone: true}"></ion-input>`

Tem algo que pode ser feito? Você tem expectativa de migrar o plugin pra versão 4 do Ionic?

**Comment by amarkes** [comment]
eita, cara vou instalar aqui a versão e vejo se rola mudar isso agora, se não paciência rsrsr

**Comment by amarkes** [comment]
Eu testei aqui na versão 4.1.1 e deu certo, porem removir as dependências, pode ser isso que tenha gerado conflito...

se o erro continuar manda o código que analiso!

**Comment by MrSparklle** [comment]
Erro continua. Criei um projeto novo do zero pra fazer o teste pra garantir que não estava fazendo nada de errado.

Segue o programa de exemplo usando Ionic 4:
https://github.com/MrSparklle/Inc4

* Pra ver o erro descomente a linha do arquivo home.page.html onde uso o brmasker

**Comment by davayd** [comment]
Faced the same problem

**Comment by amarkes** [comment]
pelo o q eu vi aqui, iônico 4 vai fuder a porra toda, ele não da acesso mais a multi value do reactiveform, vamos ter que esperar sair da beta pra ver se arruma isso, se não vamos ter que arruma uma outro solução para mascara...

**Comment by davidoween** [comment]
Faced the same problem

**Comment by amarkes** [comment]
Querem uma informação boa? Não poderão utilizar mais o br-masker no ionic 4, sabe porque?
Vamos la, vou explicar o que acontece!
O reactive form tem uma propriedade que é mult value, no 3 o ionic não usa essa propriedade, ou seja daria para uma biblioteca usar ela sem ter problemas, porem no 4 eles utilizam, fazendo com que não dê mais para utilizar :(
eu abri uma [issue](https://github.com/ionic-team/ionic/issues/15283) porem a resposta foi simples, vai reclamar para o angular :(

irei providenciar uma outra biblioteca, porem já de ante mão não tenho prazo para terminar :(


Want a good information? They will no longer be able to use br-masker in ionic 4, do you know why?
Come on, I'll explain what happens!
The reactive form has a property that is mult value, in the 3 the ionic does not use this property, that is to say it would give to a library to use it without having problems, however in the 4 they use, not giving more to use :(
I opened one [issue](https://github.com/ionic-team/ionic/issues/15283) but the answer was simple, will complain to the angular :(

I will provide another library, but beforehand I do not have time to finish

**Comment by davidoween** [comment]
Você conhece outra biblioteca para 4 iônicos?

**Comment by amarkes** [comment]
está sendo desenvolvido

**Comment by amarkes** [comment]
tenta essa aqui [br-mask](https://github.com/amarkes/br-mask)

**Comment by llinq** [comment]
@amarkes yeaaah, funcionou muito bem para mim, estava precisando disso ! obrigado !!!!!!!!!!!!!!!!!!!!
