### ISSUE TITLE
decimal: 0 is ignored and set to 2

### ISSUE THREAD

**Issue by sjucker** [amarkes/br-masker-ionic-3#58]
https://github.com/amarkes/br-masker-ionic-3/blob/3a3fc12082f4004d655e9b60815ba8d7905d98a8/src/directives/brmasker-ionic-3.ts#L61

The condition will evaluate to true `(!0)` and therefore the initially set value of 0 will be overwritten by 2.

**Comment by amarkes** [comment]
what is the reason for having a zero decimal?

**Comment by amarkes** [comment]
update mask and [use](https://github.com/amarkes/br-masker-ionic-3#example-for-thousand-number)
