### ISSUE TITLE
Mask type number

### ISSUE THREAD

**Issue by rafaelzuckerberg** [amarkes/br-masker-ionic-3#59]
Olá amigo, já vi algumas pessoas comentando a mesma situação mas com fins diferentes ,no meu caso, gostaria de saber se tem como usar o type number ao invés de text para utilização de valores em R$ (Real), grato.

**Comment by ailsoncgt** [comment]
@rafaelzuckerberg , eu testei o type="tel" e aparece o teclado numérico no celular. Só não cheguei a confirmar se ele aceita vírgula e/ou ponto. Espero ter ajudado

**Comment by amarkes** [comment]
see how to use it in the [example](https://github.com/amarkes/br-masker-ionic-3#only-example)
