### ISSUE TITLE
Can't use characters like : /- 

### ISSUE THREAD

**Issue by geraldosalazar16** [amarkes/br-masker-ionic-3#60]
Even if I do [brmasker]={} I am not able to use special characters, they are erased after i writte them.

**Comment by geraldosalazar16** [comment]
amarkes thanks for the replay already did what you suggested but the behavior still the same. Here is my package.json

{
  "name": "myApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.11.0",
    "@ionic-native/splash-screen": "~4.11.0",
    "@ionic-native/status-bar": "~4.11.0",
    "@ionic/storage": "2.1.3",
    "brmasker-ionic-3": "^1.3.1",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.11",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project"
}

**Comment by amarkes** [comment]
even using userCaracters?

**Comment by geraldosalazar16** [comment]
I am using it like this
{"userCaracters" : "true","type": "all"}

**Comment by amarkes** [comment]
I do not understand why wanting to use masks then, since you want to use all the characters...
the characters .,- are reserved for mascara only

**Comment by geraldosalazar16** [comment]
I think the same, it doesn't make much sense, but sometimes you have to do what your boss tell you to do. But anyways this was the answer I was looking for. Thanks for the replay, I am closing the issue :)
