### ISSUE TITLE
Problema ao utilizar métodos em um provider

### ISSUE THREAD

**Issue by mikaelboff** [amarkes/br-masker-ionic-3#61]
Tenho um provider chamado "util.ts" e gostaria de saber como posso injetá-lo dentro do mesmo, sendo que no provider não tenho a classe module.ts nem o decorator @NgCompontent, somente o decorator @Injectable. Pois estou tendo o seguinte erro:

```
StaticInjectorError(AppModule)[Util -> BrMaskerIonic3]: 
StaticInjectorError(Platform: core)[Util -> BrMaskerIonic3]: 
 NullInjectorError: No provider for BrMaskerIonic3!
```

Minha classe está assim:

```
import { BrMaskerIonic3 } from 'brmasker-ionic-3';

@Injectable()
export class Util {
constructor(private brMasker: BrMaskerIonic3){ }

        mascaraCPFCNPJ(valor: string) {
		return this.brMasker.writeValuePerson(valor);
	}

}
```

**Comment by amarkes** [comment]
não rola de coloca no app.module? pois nao tem outra forma se injetar sem ter declarado como um provider...

**Comment by mikaelboff** [comment]
Adicionei o BrMaskerIonic3 no array de providers e ele me retornou o seguinte erro:

```
StaticInjectorError(AppModule)[Nav -> Renderer]: 
  StaticInjectorError(Platform: core)[Nav -> Renderer]: 
    NullInjectorError: No provider for Renderer!
```
Tentei adicionar o BrMaskerModule no array de imports, porém isso também não resolveu, mesma mensagem de erro acima.

**Comment by amarkes** [comment]
mais esse erro ai é erro do provider Nav...

**Comment by mikaelboff** [comment]
Na verdade é do provider Render. Dando uma pesquisada achei uma issue no git do angular, onde um usuário diz que o "Render só funciona em Components" https://github.com/angular/angular/issues/17824#issuecomment-339937074.

E abaixo, um usuário reportou um problema com o Render, onde resolveu utilizando o RenderFactory:
https://github.com/angular/angular/issues/17824#issuecomment-351961146

Na diretiva do BrMasker também é utilizado o Render (https://github.com/amarkes/br-masker-ionic-3/blob/master/src/directives/brmasker-ionic-3.ts).

Acho que utilizando essa solução: https://github.com/angular/angular/issues/17824#issuecomment-351961146 o problema seria resolvido, poderia fazer uns testes e dar uma investigada se essa sugestão resolveria o problema? Agradecido!

**Comment by amarkes** [comment]
usa essa aqui
```
const config: BrMaskModel = new BrMaskModel();
config.person = true;
return this.brMaskerIonic3.writeCreateValue('', config);
```

**Comment by mikaelboff** [comment]
Não consigo utilizar meu app Ionic, não estou nem chamando o método que criei. Print do erro:
https://i.imgur.com/SfIDbAw.png

**Comment by amarkes** [comment]
consegue postar o código em algum lugar para ver aonde está errado?

**Comment by mikaelboff** [comment]
Reproduzi o código em: https://stackblitz.com/edit/ionic-ql8k4z?file=providers%2Futil.ts

OBS.: Apenas removendo a injeção do "BrMaskerIonic3" no construtor e removendo o método que criei o programa compila

**Comment by amarkes** [comment]
estava vendo aqui, e teria que fazer desta forma...

![captura de tela 2018-09-10 as 10 39 17](https://user-images.githubusercontent.com/6019683/45300865-dfcc0380-b4e5-11e8-9029-b009959ed7b7.png)

o útil nao está pegando o common, dai dá esse erro, e não faz sentido manter um provider dentro de outro...

**Comment by mikaelboff** [comment]
Posso não ter sido muito claro, mas na verdade não quero manter um provider dentro de outro, quero ter um método no meu provider para formatar e poder chamar esse método de qualquer página, sem precisar importar o BrMaskerIonic3 no providers da minha page.

Atualmente é necessário fazer isso em cada página que eu quero utilizar o BrMasker:
https://i.imgur.com/jeT8Rmw.png

e eu quero colocar essa função de mascarar o valor dentro do provider para não precisar fazer isso em cada página.

**Comment by mikaelboff** [comment]
Há alguma maneira de fazer isso?

**Comment by amarkes** [comment]
tenta atualizar e usar o [guide](https://github.com/amarkes/br-masker-ionic-3#use-in-services)

**Comment by mikaelboff** [comment]
Funcionou perfeitamente, muito agradecido pela implementação!!!!
