### ISSUE TITLE
Uncaught (in promise): Error: StaticInjectorError(AppModule)[Checkbox -> Renderer]

### ISSUE THREAD

**Issue by leoncarey** [amarkes/br-masker-ionic-3#63]
When I call BrMaskerIonic3 in constructor has error:
Uncaught (in promise): Error: StaticInjectorError(AppModule)[Checkbox -> Renderer]

Called: *constructor(public brMaskerIonic3: BrMaskerIonic3)*

Plz help me :)

Thanks.

**Comment by amarkes** [comment]
use [guide](https://github.com/amarkes/br-masker-ionic-3#use-in-services)

**Comment by leoncarey** [comment]
Thanks! I'll try it.

**Comment by leoncarey** [comment]
Working! Thanks a lot!
