### ISSUE TITLE
Thousand field throws an error on invalid input, instead of sanitizing it

### ISSUE THREAD

**Issue by spygi** [amarkes/br-masker-ionic-3#64]
Thanks for the library! 

https://github.com/amarkes/br-masker-ionic-3/blob/9f14212273220c3c42e10dd638f9871cab39567e/src/directives/brmasker-ionic-3.ts#L256

This throws an error when you enter characters in a "numberAndTousand" field because the variable thousands is null.

## Steps to reproduce
Create an input field with "numberAndTousand" set. Then enter only characters.

**Comment by amarkes** [comment]
but this is of the type number or tel?

**Comment by spygi** [comment]
I have't tried tel, only with and without type=num.

**Comment by amarkes** [comment]
user a [guide](https://github.com/amarkes/br-masker-ionic-3#example-for-thousand-number)

**Comment by spygi** [comment]
I used the example from the user guide, see my PR.

**Comment by amarkes** [comment]
issue close by #65
