### ISSUE TITLE
Value Mask

### ISSUE THREAD

**Issue by JoaoVFAraujo** [amarkes/br-masker-ionic-3#67]
# Valor da mascara
---
### Resumo
Quando eu coloco a mascara no input, os valores do input vem com mascara, mas não é certo salvar no banco algo com mascara, então por favor, tenta não colocar a mascara no valor do input

**Comment by thelebdev** [comment]
Got an English translation?

**Comment by JoaoVFAraujo** [comment]
already solved, thank you

**Comment by thelebdev** [comment]
Why is the issue open? @amarkes

**Comment by amarkes** [comment]
> Why is the issue open? @amarkes

What do I have to do with it?

**Comment by thelebdev** [comment]
> > Why is the issue open? @amarkes
> 
> What do I have to do with it?

I mean you're the repo's owner so.. if @JoaoVFAraujo is saying it's been solved, shouldn't you close the issue? 🤔

**Comment by amarkes** [comment]
> > > Why is the issue open? @amarkes
> > 
> > 
> > What do I have to do with it?
> 
> I mean you're the repo's owner so.. if @JoaoVFAraujo is saying it's been solved, shouldn't you close the issue? 🤔

and I have time to see these things?
