### ISSUE TITLE
Character "R" considered as reserved character

### ISSUE THREAD

**Issue by amandachagas** [amarkes/br-masker-ionic-3#7]
Hi there,

First of all, thanks for your project! It's a clean e simple lib that do the job.

I'm working in a project about vehicles and I decided to use your lib. However, it comes to a problem: Due to the use of "R" as a reserved character, I cannot register any vehicle with the letter "R" on its plate.

I do understand that you want to use "R$" as reserved character to your masks, but restricting the use of the letter "R" is not the best way. As you already use "$" as reserved, I believe that is enough to "block" the use of "R$".

So, what I suggest is to remove the "R" from the list of special characters.

**Comment by amarkes** [comment]
ok, fix error

**Comment by amandachagas** [comment]
Wow, that was fast!

I forked the repository and pushed the fix as well
