### ISSUE TITLE
Error: Uncaught (in promise): Error: No provider for BrMaskerIonic3! ???

### ISSUE THREAD

**Issue by ademir10** [amarkes/br-masker-ionic-3#73]
Boa tarde,
Não sei porque, mais não consigo adicionar o plugin ao meu projeto:
1º - npm install brmasker-ionic-3 --save
2º - fui até o meu arquivo: app.module.ts
Inseri o código:
import { BrMaskerModule } from 'brmasker-ionic-3';

e adicionei no Providers:
providers: [
    BrMaskerModule,
.
.

Ai fui no arquivo .ts da pagina que eu vou utilizar o plugin e adicionei:
import { BrMaskerIonic3, BrMaskModel } from 'brmasker-ionic-3';
..
constructor(public brMaskerIonic3: BrMaskerIonic3) { }

E ai sem nem ao menos tentar utilizar o recurso do plugin, quando eu apenas chamo a pagina, recebo esta mensagem:
Error: Uncaught (in promise): Error: No provider for BrMaskerIonic3!
Error: No provider for BrMaskerIonic3!

Como se eu não tivesse importado o plugin, vocês saberiam dizer o porque que está acontecendo isso?

Meu ambiente:
Ionic:
   ionic (Ionic CLI)  : 4.4.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.5.0
   @ionic/app-scripts : 1.3.12
Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (20 plugins total)
System:
   Android SDK Tools : 26.1.1 (/Users/dede/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   NodeJS            : v8.12.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by amarkes** [comment]
algo de errado nao esta certo, mais pelo aviso nao esta com provider registrado, no app.module apenas faz o import ao invés de declara-lo como um provider,

**Comment by ademir10** [comment]
Bom dia, Antônio! Brigadão pela ajuda!
Pois é já removi também do provider e nada acontece, continuo recebendo a mesma mensagem..

Alguma sugestão?


Em 4 de fev de 2019, à(s) 19:09, Antonio Marques <notifications@github.com> escreveu:

**Comment by amarkes** [comment]
propaganda gratuita aqui....
esta importando no lugar errado meu jovem

**Comment by ademir10** [comment]
Me desculpe pelos dados pessoais que foram inseridos junto ao meu comentário, eu devo ter respondido pelo e-mail e minha assinatura foi junto.

Com relação ao seu comentário, dizendo que estou importando incorretamente, estou fazendo exatamente como na documentação. Poderia citar em que parte do meu código está incorreta?

**Comment by amarkes** [comment]
Tens que colocar na module do componente
