### ISSUE TITLE
Aplicar mascara em valor

### ISSUE THREAD

**Issue by jeffersonmello** [amarkes/br-masker-ionic-3#75]
olá a todos, desculpe a inconveniência da issue, mas existe alguma forma de aplicar a mascara em um valor.

por exemplo estou recebendo CEP's de uma sincronização.
nesse sincronização irei aplicar a mascara através de um metodo. existe alguma forma de fazer isso?

**Comment by amarkes** [comment]
https://github.com/amarkes/br-masker-ionic-3/blob/master/README.md#features
